os:
  - linux

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libboost-program-options-dev
      - libboost-system-dev
      - libgtest-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7

  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test

